### ISSUE TITLE
[UI/UX] Game menu attempt

### ISSUE THREAD

**Issue by Ninjseal** [alexgavrila/LabirintulAugmentat#11]
Research and try to implement the game menu with simple buttons, title, background (animations?).
The game menu should consist of a main menu, a shop menu, credits menu (authors/contributors) and a button that starts the game.
The implementation shall be minimal for now.

**Comment by Ninjseal** [comment]
@alexandru-balan Any progress regarding this?

**Comment by alexandru-balan** [comment]
Not anything tangible, watched some tutorials only. I'll start working on this tomorrow and push a new branch by the end of the day.

**Comment by Ninjseal** [comment]
Ok. Thanks for your response :+1:

**Comment by alexandru-balan** [comment]
### Subtasks:

- [ ] Make the UI scale better on all screen sizes
- [ ] Polish the start menu UI
- [ ] Create the shop interface 
- [ ] Add credits menu
